import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { User } from 'src/app/models/user.model';
import { UserService } from 'src/app/services/user.service';


@Component({
  selector: 'app-add-new-user',
  templateUrl: './add-new-user.component.html',
  styleUrls: ['./add-new-user.component.css']
})
export class AddNewUserComponent implements OnInit {

  userForm!: FormGroup;

  constructor(private userService: UserService) {}

  ngOnInit(): void {

    this.userForm = new FormGroup({

      // ID will be generated by UserService
      id: new FormControl(0),

      firstName: new FormControl('', [
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(50)
      ]),

      lastName: new FormControl('', [
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(50)
      ]),

      email: new FormControl('', [
        Validators.required,
        Validators.email
      ]),

      mobile: new FormControl('', [
        Validators.required,
        Validators.pattern('^[0-9]{10}$')
      ]),

      city: new FormControl('', [
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(50)
      ]),

      password: new FormControl('', [
        Validators.required,
        Validators.minLength(8)
      ])

    });
  }


  onSubmit(): void {

    // Check validation
    if (this.userForm.invalid) {

      this.userForm.markAllAsTouched();

      return;
    }

    
    const user: User = this.userForm.value;

    console.log('User before adding:', user);

    
    this.userService.addUser(user);

    console.log('User added successfully');

    
    this.userForm.reset({
      id: 0,
      firstName: '',
      lastName: '',
      email: '',
      mobile: '',
      city: '',
      password: ''
    });
  }




  
  

  get firstName(): FormControl {
    return this.userForm.get('firstName') as FormControl;
  }

  get lastName(): FormControl {
    return this.userForm.get('lastName') as FormControl;
  }

  get email(): FormControl {
    return this.userForm.get('email') as FormControl;
  }

  get mobile(): FormControl {
    return this.userForm.get('mobile') as FormControl;
  }

  get city(): FormControl {
    return this.userForm.get('city') as FormControl;
  }

  get password(): FormControl {
    return this.userForm.get('password') as FormControl;
  }

}